print("=[1]=====================")
print("NIS => 232428")
input()
print("Nama => Vincent Timothy")
input()
print("Kelas => 11.2")
input()
print("Jurusan => IPA Teknik")
input()
print("Jenis Kelamin => L")
input()
print("Alamat => Perum Kedung Waringin Blok B4/19")
input()
print("=[2]=====================")
print("NIS => 232422")
input()
print("Nama => Sabian Putra")
input()
print("Kelas => 11.2")
input()
print("Jurusan => IPA Teknik")
input()
print("Jenis Kelamin => L")
input()
print("Alamat => Galuh Mas Blok C10")
input()
print("=[2]=====================")
print("NIS => 232407")
input()
print("Nama => Daniel Stevfarel")
input()
print("Kelas => 11.2")
input()
print("Jurusan => IPA Teknik")
input()
print("Jenis Kelamin => L")
input()
print("Alamat => Galuh Mas Blok C10")
input()
print("=========================")